services:
  nginx:
    image: skpr/nginx-php-fpm:dev-v2-latest
    volumes:
      - ./:/data
      - ./docker/development/nginx/default.conf:/etc/nginx/default.conf
    ports:
      - "${WEB_PORT:-8080}:8080"
      - "${MYSQL_PORT:-3306}:3306"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-fpm:
    image: skpr/php-fpm:8.3-dev-v2-latest
    command:
        - "php-fpm"
        - "-F"
    network_mode: service:nginx
    volumes:
      - ./:/data
    env_file:
      - .env

  php-cli:
      image: skpr/php-cli:8.3-dev-v2-stable
      tty: true
      stdin_open: true
      network_mode: service:nginx
      volumes:
          - ./:/data
      env_file: ['.env']

  node:
      image: skpr/node:22-v2-stable
      tty: true
      stdin_open: true
      network_mode: service:nginx
      volumes:
          - ./:/data
      env_file: ['.env']

  mysql-default:
    image: docker.io/skpr/mysql-empty:8.x-v3-edge
    network_mode: service:nginx
    healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        interval: 1s
        retries: 60

  redis:
    image: redis:alpine
    network_mode: service:nginx
