services:
  nginx:
    image: skpr/nginx-php-fpm:dev-v2-latest
    volumes:
      - ./:/data
      - ./docker/development/nginx/default.conf:/etc/nginx/default.conf
    ports:
      - "${WEB_PORT:-8080}:8080"
      - "${MYSQL_PORT:-3306}:3306"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-fpm:
    image: skpr/php-fpm:8.3-dev-v2-latest
    command:
        - "php-fpm"
        - "-F"
    network_mode: service:nginx
    volumes:
      - ./:/data
    env_file:
      - .env

#  workspace:
#   # For the workspace service, we will also create a custom image to install and setup all the necessary stuff.
#    build:
#      context: .
#      dockerfile: ./docker/development/workspace/Dockerfile
#      args:
#        UID: ${UID:-1000}
#        GID: ${GID:-1000}
#        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
#        XDEBUG_MODE: develop,coverage,debug,profile
#        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
#        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
#        XDEBUG_LOG: /dev/stdout
#        XDEBUG_LOG_LEVEL: 0
#    tty: true  # Enables an interactive terminal
#    stdin_open: true  # Keeps standard input open for 'docker exec'
#    env_file:
#      - .env
#    volumes:
#      - ./:/var/www
#    networks:
#      - laravel-development

  mysql-default:
    image: docker.io/skpr/mysql-empty:8.x-v3-edge
    network_mode: service:nginx
    healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        interval: 1s
        retries: 60

  redis:
    image: redis:alpine
    network_mode: service:nginx
